### ISSUE TITLE
Recuperar des de json no recupera la data d'examen

### ISSUE THREAD

**Issue by saludes** [rafelamer/examens-python#2]
```
$ examen.py` --examen=examen.tex --estudiants=estudiants.csv --problemes=4 --json
$ mv tex tex.old
$ examen.py --examen=examen.tex --estudiants=estudiants.csv --dades=examen001.json
 ````
llavors
```$ diff tex/cano-medina-carles.tex tex.old/cano-medina-carles.tex```
dóna:
```
5c5
< \data{DATAEXAMEN}
---
> \data{\dataexamen{1}{1}{2022}}`
```

**Comment by rafelamer** [comment]
Ja ho he solucionat. Fins ara quan llegia les dades del fitxer JSON no calia utilitzar el fitxer Problemes.py, però ara sí, ja que hi podem tenir definida la funció dataexamen()
